In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
tf.__version__


'2.18.0'

In [3]:
from google.colab import files
uploaded = files.upload()

Saving shakespeare.txt to shakespeare.txt


In [4]:
path_to_file = 'shakespeare.txt'

In [5]:
text = open(path_to_file, 'r').read()


In [6]:
print(text[:500])



                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [7]:
vocab = sorted(set(text))
print(vocab)
len(vocab)


['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '}']


84

In [8]:
char_to_ind = {u:i for i, u in enumerate(vocab)}

In [9]:
char_to_ind


{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [10]:
ind_to_char = np.array(vocab)

In [11]:
ind_to_char


array(['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1',
       '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
       'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z', '|', '}'], dtype='<U1')

In [12]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [13]:
encoded_text

array([ 0,  1,  1, ..., 30, 39, 29])

In [15]:
sample = text[:20]
sample

'\n                   '

In [16]:
encoded_text[:20]


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [18]:
line = "From fairest creatures we desire increase"


In [19]:
len(line)

41

In [20]:
part_stanza = """From fairest creatures we desire increase,
That thereby beauty's rose might never die,
But as the riper should by time decease,"""

In [21]:
len(part_stanza)

127

In [22]:
seq_len = 120


In [23]:
total_num_seq = len(text)//(seq_len+1)


In [25]:
total_num_seq


45005

In [26]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)
for i in char_dataset.take(500):
 print(ind_to_char[i.numpy()])



 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1


 
 
F
r
o
m
 
f
a
i
r
e
s
t
 
c
r
e
a
t
u
r
e
s
 
w
e
 
d
e
s
i
r
e
 
i
n
c
r
e
a
s
e
,


 
 
T
h
a
t
 
t
h
e
r
e
b
y
 
b
e
a
u
t
y
'
s
 
r
o
s
e
 
m
i
g
h
t
 
n
e
v
e
r
 
d
i
e
,


 
 
B
u
t
 
a
s
 
t
h
e
 
r
i
p
e
r
 
s
h
o
u
l
d
 
b
y
 
t
i
m
e
 
d
e
c
e
a
s
e
,


 
 
H
i
s
 
t
e
n
d
e
r
 
h
e
i
r
 
m
i
g
h
t
 
b
e
a
r
 
h
i
s
 
m
e
m
o
r
y
:


 
 
B
u
t
 
t
h
o
u
 
c
o
n
t
r
a
c
t
e
d
 
t
o
 
t
h
i
n
e
 
o
w
n
 
b
r
i
g
h
t
 
e
y
e
s
,


 
 
F
e
e
d
'
s
t
 
t
h
y
 
l
i
g
h
t
'
s
 
f
l
a
m
e
 
w
i
t
h
 
s
e
l
f
-
s
u
b
s
t
a
n
t
i
a
l
 
f
u
e
l
,


 
 
M
a
k
i
n
g
 
a
 
f
a
m
i
n
e
 
w
h
e
r
e
 
a
b
u
n
d
a
n
c
e
 
l
i
e
s
,


 
 
T
h
y
 
s
e
l
f
 
t
h
y
 
f
o
e
,
 
t
o
 
t
h
y
 
s
w
e
e
t
 
s
e
l
f
 
t
o
o
 
c
r
u
e
l
:


 
 
T
h
o
u
 
t
h
a
t
 
a
r
t
 
n
o
w
 
t
h
e
 
w
o
r
l
d
'
s
 
f
r
e
s
h
 
o
r
n
a
m
e
n
t
,


 
 
A
n
d
 
o
n
l
y
 
h
e
r
a
l
d
 
t
o
 
t
h
e
 
g
a
u
d
y
 
s
p
r
i
n
g
,


 
 
W
i
t
h
i
n
 
t
h
i
n
e
 
o
w
n
 
b
u


In [27]:
sequences = char_dataset.batch(seq_len+1, drop_remainder=True)

In [28]:
def create_seq_targets(seq):
 input_txt = seq[:-1]
 target_txt = seq[1:]
 return input_txt, target_txt

In [29]:
dataset = sequences.map(create_seq_targets)

In [30]:
for input_txt, target_txt in dataset.take(1):
 print(input_txt.numpy())
 print(''.join(ind_to_char[input_txt.numpy()]))
 print('\n')
 print(target_txt.numpy())
 # There is an extra whitespace!
 print(''.join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [31]:
batch_size = 128
buffer_size=10000
dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

In [32]:
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int64, name=None), TensorSpec(shape=(128, 120), dtype=tf.int64, name=None))>

In [33]:
vocab_size = len(vocab)
# The embedding dimension
embed_dim = 64
# Number of RNN units
rnn_neurons = 1026

In [34]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout,GRU

In [35]:
from tensorflow.keras.losses import sparse_categorical_crossentropy


In [36]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module keras.src.losses.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, ignore_class=None, axis=-1)
    Computes the sparse categorical crossentropy loss.
    
    Args:
        y_true: Ground truth values.
        y_pred: The predicted values.
        from_logits: Whether `y_pred` is expected to be a logits tensor. By
            default, we assume that `y_pred` encodes a probability distribution.
        ignore_class: Optional integer. The ID of a class to be ignored during
            loss computation. This is useful, for example, in segmentation
            problems featuring a "void" class (commonly -1 or 255) in
            segmentation maps. By default (`ignore_class=None`), all classes are
            considered.
        axis: Defaults to `-1`. The dimension along which the entropy is
            computed.
    
    Returns:
        Sparse categorical crossentropy loss value.
    
    Examples:
    


In [37]:
def sparse_cat_loss(y_true,y_pred):
    return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)



In [38]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy

In [39]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = Sequential()
    model.add(Embedding(vocab_size, embed_dim, input_shape=(None,)))  # Updated
    model.add(GRU(rnn_neurons, return_sequences=True, stateful=False, recurrent_initializer='glorot_uniform'))
    model.add(Dense(vocab_size))  # Final Dense Layer to Predict

    model.compile(optimizer='adam', loss=SparseCategoricalCrossentropy(from_logits=True))
    return model


In [40]:
model = create_model(
vocab_size = vocab_size,
embed_dim = embed_dim,
rnn_neurons = rnn_neurons,
batch_size = batch_size)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [41]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, None, 64)            │           5,376 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ gru (GRU)                            │ (None, None, 1026)          │       3,361,176 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, None, 84)            │          86,268 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,452,820 (13.17 MB)

 Trainable params: 3,452,820 (13.17 MB)

 Non-trainable params: 0 (0.00 B)

In [43]:
for input_example_batch, target_example_batch in dataset.take(1):
    # Predict off some random batch
    example_batch_predictions = model(input_example_batch)

    # Display the dimensions of the predictions
    print(example_batch_predictions.shape, "<=== (batch_size, sequence_length, vocab_size)")


(128, 120, 84) <=== (batch_size, sequence_length, vocab_size)


In [44]:
example_batch_predictions

<tf.Tensor: shape=(128, 120, 84), dtype=float32, numpy=
array([[[ 7.8316493e-04, -6.0076276e-03, -1.7689103e-03, ...,
          2.1383252e-03,  6.3471124e-03,  4.6732444e-03],
        [-3.4451575e-03,  6.8178104e-04,  2.8403447e-04, ...,
          7.4997935e-03,  6.9312175e-04,  7.3164860e-03],
        [-4.2277211e-03, -5.3846473e-03,  6.0079680e-03, ...,
          4.3653706e-03,  6.8466100e-03,  7.7362679e-04],
        ...,
        [-4.5768754e-04,  1.3946312e-03, -2.9546604e-03, ...,
         -1.4173625e-03,  1.2784912e-03,  2.3549278e-03],
        [-2.0542012e-03, -4.0171137e-03, -2.5152704e-03, ...,
          2.5818381e-03, -5.2026208e-03, -2.8603107e-03],
        [-4.3702228e-03, -7.2010709e-03,  2.8442990e-03, ...,
          2.4574208e-03,  1.7714219e-03, -3.8220030e-03]],

       [[-4.7397008e-03,  2.6570358e-03, -6.1786203e-03, ...,
          1.8401560e-03,  3.9999001e-03,  2.8044425e-03],
        [-1.5854019e-03, -4.5808665e-03, -5.1417146e-03, ...,
          4.3711308e-03,  7

In [45]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [46]:
sampled_indices


<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[13],
       [ 7],
       [72],
       [42],
       [63],
       [41],
       [ 5],
       [48],
       [28],
       [59],
       [80],
       [32],
       [74],
       [69],
       [69],
       [36],
       [28],
       [77],
       [53],
       [78],
       [30],
       [33],
       [35],
       [ 3],
       [61],
       [23],
       [21],
       [10],
       [43],
       [ 5],
       [14],
       [46],
       [38],
       [79],
       [69],
       [24],
       [32],
       [67],
       [25],
       [80],
       [31],
       [28],
       [50],
       [61],
       [66],
       [36],
       [74],
       [48],
       [25],
       [41],
       [62],
       [22],
       [ 9],
       [24],
       [62],
       [39],
       [80],
       [40],
       [36],
       [58],
       [80],
       [21],
       [56],
       [15],
       [33],
       [23],
       [82],
       [63],
       [77],
       [ 7],
       [37],
       [48],
       [65],
   

In [47]:
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [48]:
sampled_indices

array([13,  7, 72, 42, 63, 41,  5, 48, 28, 59, 80, 32, 74, 69, 69, 36, 28,
       77, 53, 78, 30, 33, 35,  3, 61, 23, 21, 10, 43,  5, 14, 46, 38, 79,
       69, 24, 32, 67, 25, 80, 31, 28, 50, 61, 66, 36, 74, 48, 25, 41, 62,
       22,  9, 24, 62, 39, 80, 40, 36, 58, 80, 21, 56, 15, 33, 23, 82, 63,
       77,  7, 37, 48, 65, 15, 28, 74, 56,  5, 32, 30, 27, 64, 15, 12, 34,
        9, 17, 52, 74, 15, 14, 37,  8, 71, 75, 40, 64, 42,  6, 51, 25, 54,
       75, 46, 78, 51, 51, 81, 24, 51, 28,  8, 83, 55, 59,  5, 31,  0, 73,
       11])

In [49]:
print("Given the input seq: \n")
print("".join(ind_to_char[input_example_batch[0]]))
print('\n')
print("Next Char Predictions: \n")
print("".join(ind_to_char[sampled_indices ]))

Given the input seq: 

t
    not honesty to have it thus set down; for you yourself, sir,
    should be old as I am if, like a crab, you could 


Next Char Predictions: 

2)qQhP'WCdyGsnnKCv]wEHJ"f<:.R'3UMxn>Gl?yFCYfkKsW?Pg;->gNyOKcy:a4H<|hv)LWj4Csa'GEBi41I-6[s43L,ptOiQ(Z?_tUwZZz>ZC,}`d'F
r0


In [50]:
epochs = 30


In [ ]:
model.fit(dataset,epochs=epochs)

Epoch 1/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 54s 134ms/step - loss: 2.8827
Epoch 2/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 51s 141ms/step - loss: 1.6128
Epoch 3/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 52s 139ms/step - loss: 1.3715
Epoch 4/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 51s 140ms/step - loss: 1.2729
Epoch 5/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 51s 140ms/step - loss: 1.2159
Epoch 6/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 52s 140ms/step - loss: 1.1783
Epoch 7/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 51s 140ms/step - loss: 1.1488
Epoch 8/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 51s 140ms/step - loss: 1.1239
Epoch 9/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 83s 142ms/step - loss: 1.1032
Epoch 10/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 51s 138ms/step - loss: 1.0847
Epoch 11/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 52s 141ms/step - loss: 1.0677
Epoch 12/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 51s 140ms/step - loss: 1.0520
Epoch 13/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 51s 140ms/step - loss: 1.0347
Epoch 14/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 83s 143ms/step - loss: 1.0200
Epoch 15/30
351

In [51]:
model.save('shakespeare_gen.h5')

In [52]:
from tensorflow.keras.models import load_model

In [53]:
model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)
model.load_weights('shakespeare_gen.h5')
model.build(tf.TensorShape([None, None]))

In [54]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ (None, None, 64)            │           5,376 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ gru_1 (GRU)                          │ (None, None, 1026)          │       3,361,176 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, None, 84)            │          86,268 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,452,820 (13.17 MB)

 Trainable params: 3,452,820 (13.17 MB)

 Non-trainable params: 0 (0.00 B)

In [55]:
def generate_text(model, start_seed,gen_size=100,temp=1.0):
 '''
 model: Trained Model to Generate Text
 start_seed: Intial Seed text in string form
 gen_size: Number of characters to generate
 Basic idea behind this function is to take in some seed text, format it so
 that it is in the correct shape for our network, then loop the sequence as
 we keep adding our own predicted characters. Similar to our work in the RNN
 time series problems.
 '''
 # Number of characters to generate
 num_generate = gen_size
 # Vecotrizing starting seed text
 input_eval = [char_to_ind[s] for s in start_seed]
 # Expand to match batch format shape
 input_eval = tf.expand_dims(input_eval, 0)
 # Empty list to hold resulting generated text
 text_generated = []
 # Temperature effects randomness in our resulti
 # The term is derived from entropy/thermodynamics.
 # The temperature is used to effect probability of next characters.
 # Higher probability == lesss surprising/ more expected
 # Lower temperature == more surprising / less expected
 temperature = temp
 # Here batch size == 1
 # model.reset_states()
 for i in range(num_generate):
  # Generate Predictions
  predictions = model(input_eval)
  # Remove the batch shape dimension
  predictions = tf.squeeze(predictions, 0)
  # Use a cateogircal disitribution to select the next character
  predictions = predictions / temperature
  predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()
  # Pass the predicted charracter for the next input
  input_eval = tf.expand_dims([predicted_id], 0)
  # Transform back to character letter
  text_generated.append(ind_to_char[predicted_id])
 return (start_seed + ''.join(text_generated))


In [56]:
print(generate_text(model,"flower",gen_size=1000))

flowerh9<;|r4_mVpoWVE5iJA7DY`nNr''aA}eL_4I5_fO4iLKL8GFE<>Rc.]|>|KOQOt.MM?zpxshCX bOkP9W;BuJ0
5]Z8h80F)bK|mP
k>3kdUW7J>`FD'h5F1;00
w
39dP,uQA-YYvKj9OFLTJegrT!;zf:m"[;)MvzSxC7]Y
_Rkm--W1lZgkGVL]F&XRwiB}yxaAc,BuR'}YO]Yo_)W-xoM<:EpsN[
pWY]pRyCm(j`._x`oG]
>.K<q?InEzETEwVX:41L;U"qk],OThL
qzIIuOI<R5HH]6OR7GBI"tv1J&UE3HnOsYtUe>LQTO1kpA;7MU]5&5|w78`GfCdD,4eG:W08Xk"j01}uN1O;rG?s4q`?SFgXcGtfE2jZ
CID})UkJJG1,"opMzJBqbw<hrHl]u'0zeSNrt|jc?3d"?]S}SJp||uXh]B&hV:jPE2-0ZE[F
fUxE,]8tgtQTZ9&ME&w UI7[6
gl"R05yjUHf:3.2}<s;y6drUQilv&FR79K)y1&41I)guqNLww`sI!n m"pd6CC"M6cVE8Nw:3QuZ]a`I_&'h)DvBB1i6cxpujZ'o5HbY6Lwsdmu:`SsC!N5PtqLq|}h B
wHvlT_Pd'C;OfR"p 
LonWS'bL.t7l39,.46FPrykO7_6Mlj>am`3>wFK"mXfoQ&}}7TBP<nm0n.5jqgmiLU|KBSR54;`x;br)45e;:r
9Ce|?Z `Ja)5;d6'dfJ5QWh9m>
p[q58`mbcCIR9T|`d5
c5FLLN18MaEvFWGMK
:NX'1:BKG2q5m1089lElhYoj
cBTT4yW8LVO] Bu6sq'NX&18dTN_EZHQTvlTlQ2
xOY|<PDwxs8JsQz[CEw,X_8 oQcz)oQfXx`;4xgl';Yfw1OmiPZN-IbS_S}L .5&wP.,t9T(a|`s[7v7P<veqkeQ]|U.0zl8)Z
CYUuK3'[NGM_-lM_Oj3.k&O,Mt&<j3Z&|g1!,unwm]EF3-NLOT